# sub Makefile

# inclusions
INCFLAGS:= -Iince -Iinci -I../common/ince -I../volume/ince -I../crypto/ince -I../fuse/ince

# Objects needed
CFILES:= $(shell find src -name '*.cpp')

# actual compilation
include ../Makefile

