# sub Makefile

# inclusions
INCLUDES:=ince inci ../common/ince ../volume/ince

# Objects needed
CXXFILES:= $(shell find src -name '*.cpp')

# C files for e2fsprogs
CFILES+= src/e2fsprogs/fuse2fs.c

# actual compilation
include rules.mk

