# sub Makefile

# inclusions
INCLUDES:= ince inci ../common/ince ../volume/ince ../crypto/ince ../fuse/ince

# Objects needed
CXXFILES:= $(shell find src -name '*.cpp')

# actual compilation
include rules.mk

