name: Basic

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Apt update'
        run: sudo apt update
      - name: 'Install libfuse-dev e2fslibs-dev'
        # This job installs the required libraries to build the core (FUSE + E2FS)
        run: sudo apt install libfuse-dev e2fslibs-dev
      - name: 'Install Qt5 libs and modules'
        # This job installs the required libraries to build the Qt interface (Qt5 qml quick labs ++)
        run: sudo apt install qt5-default qtdeclarative5-dev qml-module-qtquick2 qml-module-qtquick-controls qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
      - name: 'Building whole project'
        run: make
      - name: 'Upload common test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_common
          path: bin/ut/ut_common
          retention-days: 1
      - name: 'Upload crypto test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_crypto
          path: bin/ut/ut_crypto
          retention-days: 1
      - name: 'Upload volume test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_volume
          path: bin/ut/ut_volume
          retention-days: 1
      - name: 'Upload gc_cmdline binary'
        uses: actions/upload-artifact@v2
        with:
          name: gc_cmdline
          path: bin/gc_cmdline
          retention-days: 1
  ut:
    name: 'Unit tests'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 'Getting common built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_common
      - name: 'Getting crypto built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_crypto
      - name: 'Getting volume built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_volume
      - name: 'Giving execution rights to binaries'
        run: sudo chmod a+x ./ut_*
      - name: 'Running common test'
        run: ./ut_common
      - name: 'Running crypto test'
        run: ./ut_crypto
      - name: 'Running volume test'
        run: ./ut_volume
  it:
    name: 'Integration tests'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Getting cmdline built binary'
        uses: actions/download-artifact@v2
        with:
          name: gc_cmdline
          path: bin
      - name: 'Giving execution rights to binaries'
        run: sudo chmod a+x ./bin/gc_*
      - name: 'Uncommenting allow_other to the global fuse options'
        run: sudo sed -b -i 's/#user_allow_other/user_allow_other/g' /etc/fuse.conf
      - name: 'Running cmdline integration tests'
        run: cd it/cmdline/ && ./mainTests.sh
