name: Basic

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Apt update'
        run: sudo apt update
      - name: 'Install libfuse-dev libacl1-dev'
        # This job installs the required libraries to build the core (FUSE + lwext4)
        run: sudo apt install libfuse-dev libacl1-dev
      - name: 'Install Qt5 libs and modules'
        # This job installs the required libraries to build the Qt interface (Qt5 qml quick labs ++)
        run: sudo apt install qt5-default qtdeclarative5-dev qml-module-qtquick2 qml-module-qtquick-controls qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
      - name: 'Install mingw-w64'
        # This job installs the required libraries to build for Windows (Not needed for linux builds)
        run: sudo apt install mingw-w64
      - name: 'Building whole project'
        run: make -j4
      - name: 'Building unit tests for windows'
        run: make -j4 P=windows ut_common ut_crypto ut_volume
      - name: 'Upload common test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_common_lin
          path: build/linux/release/bin/ut/ut_common
          retention-days: 1
      - name: 'Upload crypto test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_crypto_lin
          path: build/linux/release/bin/ut/ut_crypto
          retention-days: 1
      - name: 'Upload volume test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_volume_lin
          path: build/linux/release/bin/ut/ut_volume
          retention-days: 1
      - name: 'Upload gc_cmdline binary'
        uses: actions/upload-artifact@v2
        with:
          name: gc_cmdline_lin
          path: build/linux/release/bin/gc_cmdline
          retention-days: 1
      - name: 'Upload common test binary for windows'
        uses: actions/upload-artifact@v2
        with:
          name: ut_common_win
          path: build/windows/release/bin/ut/ut_common
          retention-days: 1
      - name: 'Upload crypto test binary for windows'
        uses: actions/upload-artifact@v2
        with:
          name: ut_crypto_win
          path: build/windows/release/bin/ut/ut_crypto
          retention-days: 1
      - name: 'Upload volume test binary for windows'
        uses: actions/upload-artifact@v2
        with:
          name: ut_volume_win
          path: build/windows/release/bin/ut/ut_volume
          retention-days: 1
  ut:
    name: 'Unit tests'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 'Getting common built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_common_lin
      - name: 'Getting crypto built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_crypto_lin
      - name: 'Getting volume built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_volume_lin
      - name: 'Giving execution rights to binaries'
        run: sudo chmod a+x ./ut_*
      - name: 'Running common test'
        run: ./ut_common
      - name: 'Running crypto test'
        run: ./ut_crypto
      - name: 'Running volume test'
        run: ./ut_volume
  ut_win:
    name: 'Unit tests for windows'
    needs: build
    runs-on: windows-latest

    steps:
      - name: 'Getting common built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_common_win
      - name: 'Getting crypto built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_crypto_win
      - name: 'Getting volume built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_volume_win
      - name: 'Renaming files to add exe extension'
        shell: cmd
        run: ren *. *.exe
      - name: 'Running common test'
        shell: cmd
        run: .\ut_common.exe
      - name: 'Running crypto test'
        shell: cmd
        run: .\ut_crypto.exe
      - name: 'Running volume test'
        shell: cmd
        run: .\ut_volume.exe
  it:
    name: 'Integration tests'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Getting cmdline built binary'
        uses: actions/download-artifact@v2
        with:
          name: gc_cmdline_lin
          path: bin
      - name: 'Giving execution rights to binaries'
        run: sudo chmod a+x ./bin/gc_*
      - name: 'Uncommenting allow_other to the global fuse options'
        run: sudo sed -b -i 's/#user_allow_other/user_allow_other/g' /etc/fuse.conf
      - name: 'Running cmdline integration tests'
        run: cd it/cmdline/ && ./mainTests.sh

