name: Build and test all targets

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Install libfuse-dev'
        run: sudo apt install libfuse-dev
      - name: 'Building whole project'
        run: make
      - name: 'Upload common test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_common
          path: bin/ut/ut_common
          retention-days: 1
      - name: 'Upload crypto test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_crypto
          path: bin/ut/ut_crypto
          retention-days: 1
      - name: 'Upload volume test binary'
        uses: actions/upload-artifact@v2
        with:
          name: ut_volume
          path: bin/ut/ut_volume
          retention-days: 1
  ut:
    name: 'Unit tests'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 'Getting common built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_common
      - name: 'Getting crypto built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_crypto
      - name: 'Getting volume built binary'
        uses: actions/download-artifact@v2
        with:
          name: ut_volume
      - name: 'Giving execution rights to binaries'
        run: sudo chmod a+x ./ut_*
      - name: 'Running common test'
        run: ./ut_common
      - name: 'Running crypto test'
        run: ./ut_crypto
      - name: 'Running volume test'
        run: ./ut_volume
